export const mockProducts = [
  {
    productId: "2673628",
    glNumber: "2673628",
    packSize: "12/12 OZ",
    brand: "Applegate Naturals",
    title: "Cheese, American, Yellow, Sliced, Print Wrapped",
    rating: 3.5,
    tags: ["cmpContract", "direct", "recentPurchase", "scoop", "onML"],
    priceCS: 42.80,
    priceEA: 3.57,
    savings: "SAVE $2 OFF / CS",
    lineNumber: 1,
    imageUrl: "https://images.openfoodfacts.org/images/products/002/531/700/6941/front_en.5.400.jpg",
    isSponsored: true,
    sponsoredLabel: "Featured"
  },
  {
    productId: "2673629",
    glNumber: "2673629",
    packSize: "12/12 OZ",
    brand: "Applegate Naturals",
    title: "Cheese, American, White, Sliced, Print Wrapped",
    rating: 3.5,
    tags: ["cmpContract", "direct"],
    priceCS: 42.80,
    priceEA: 3.57,
    savings: "SAVE $2 OFF / CS",
    lineNumber: 2,
    imageUrl: "https://images.openfoodfacts.org/images/products/002/531/777/7001/front_en.5.400.jpg",
    isSponsored: false,
    sponsoredLabel: null
  },
  {
    productId: "2673630",
    glNumber: "2673630",
    packSize: "6/5 LB",
    brand: "Sargento",
    title: "Mozzarella, Low Moisture, Whole Milk, Block",
    rating: 4.2,
    tags: ["cmpContract", "onML"],
    priceCS: 138.50,
    priceEA: 23.08,
    savings: "SAVE $5 OFF / CS",
    lineNumber: 3,
    imageUrl: "https://images.openfoodfacts.org/images/products/004/610/000/1257/front_en.55.400.jpg",
    isSponsored: false,
    sponsoredLabel: null
  },
  {
    productId: "2673631",
    glNumber: "2673631",
    packSize: "10/8 OZ",
    brand: "BelGioioso",
    title: "Mozzarella, Fresh, Log, Water Packed",
    rating: 4.1,
    tags: ["direct", "recentPurchase"],
    priceCS: 74.90,
    priceEA: 7.49,
    savings: "SAVE $6 OFF / CS",
    lineNumber: 4,
    imageUrl: "https://images.openfoodfacts.org/images/products/003/114/200/0696/front_en.39.400.jpg",
    isSponsored: false,
    sponsoredLabel: null
  },
  {
    productId: "2673632",
    glNumber: "2673632",
    packSize: "6/5 LB",
    brand: "Stella",
    title: "Mozzarella, Low Moisture, Part Skim, Shredded",
    rating: 4.3,
    tags: ["direct", "scoop"],
    priceCS: 112.20,
    priceEA: 18.70,
    savings: "SAVE $3.80 OFF / CS",
    lineNumber: 5,
    // Sargento shredded whole milk mozzarella — same product form factor
    imageUrl: "https://images.openfoodfacts.org/images/products/004/610/040/0104/front_en.26.400.jpg",
    isSponsored: true,
    sponsoredLabel: "Featured"
  },
  {
    productId: "2673633",
    glNumber: "2673633",
    packSize: "10/10 OZ",
    brand: "Hormel Foods",
    title: "Pepperoni, Sliced, 16–18 ct, Pouch",
    rating: 4.5,
    tags: ["cmpContract", "recentPurchase"],
    priceCS: 89.40,
    priceEA: 8.94,
    savings: "SAVE $1.50 OFF / CS",
    lineNumber: 6,
    imageUrl: "https://images.openfoodfacts.org/images/products/003/760/039/8855/front_en.46.400.jpg",
    isSponsored: false,
    sponsoredLabel: null
  },
  {
    productId: "2673634",
    glNumber: "2673634",
    packSize: "4/5 LB",
    brand: "Tillamook",
    title: "Cheddar, Sharp, Aged, Yellow, Block",
    rating: 4.6,
    tags: ["cmpContract"],
    priceCS: 104.00,
    priceEA: 26.00,
    savings: "SAVE $3.50 OFF / CS",
    lineNumber: 7,
    imageUrl: "https://images.openfoodfacts.org/images/products/007/283/001/1044/front_en.27.400.jpg",
    isSponsored: false,
    sponsoredLabel: null
  },
  {
    productId: "2673635",
    glNumber: "2673635",
    packSize: "12/1 LB",
    brand: "Cabot",
    title: "Cheddar, Vermont White, Sliced, Deli Style",
    rating: 3.9,
    tags: ["cmpContract", "scoop", "onML"],
    priceCS: 96.00,
    priceEA: 8.00,
    savings: "SAVE $2.75 OFF / CS",
    lineNumber: 8,
    imageUrl: "https://images.openfoodfacts.org/images/products/265/220/100/7074/front_en.3.400.jpg",
    isSponsored: false,
    sponsoredLabel: null
  },
  {
    productId: "2673636",
    glNumber: "2673636",
    packSize: "6/2.5 LB",
    brand: "Land O'Lakes",
    title: "Butter, Unsalted, Solid, Grade AA",
    rating: 4.8,
    tags: ["cmpContract", "direct", "recentPurchase", "onML"],
    priceCS: 112.50,
    priceEA: 18.75,
    savings: "SAVE $4 OFF / CS",
    lineNumber: 9,
    imageUrl: "https://images.openfoodfacts.org/images/products/003/450/015/1504/front_en.22.400.jpg",
    isSponsored: false,
    sponsoredLabel: null
  },
  {
    productId: "2673637",
    glNumber: "2673637",
    packSize: "12/1 LB",
    brand: "Organic Valley",
    title: "Cream Cheese, Plain, Organic, Block",
    rating: 3.8,
    tags: ["direct", "scoop"],
    priceCS: 108.00,
    priceEA: 9.00,
    savings: "SAVE $2.50 OFF / CS",
    lineNumber: 10,
    imageUrl: "https://images.openfoodfacts.org/images/products/009/396/621/1016/front_en.20.400.jpg",
    isSponsored: true,
    sponsoredLabel: "Featured"
  },
  {
    productId: "2673638",
    glNumber: "2673638",
    packSize: "2/5 LB",
    brand: "Philadelphia",
    title: "Cream Cheese, Plain, Brick, Foodservice",
    rating: 4.4,
    tags: ["cmpContract", "direct", "recentPurchase"],
    priceCS: 54.90,
    priceEA: 27.45,
    savings: "SAVE $3 OFF / CS",
    lineNumber: 11,
    imageUrl: "https://images.openfoodfacts.org/images/products/762/220/169/3916/front_en.3.400.jpg",
    isSponsored: false,
    sponsoredLabel: null
  },
  {
    productId: "2673639",
    glNumber: "2673639",
    packSize: "12/12 OZ",
    brand: "Kraft",
    title: "Cheddar, Mild, Shredded, Fancy",
    rating: 4.0,
    tags: ["direct", "onML"],
    priceCS: 68.40,
    priceEA: 5.70,
    savings: "SAVE $1.90 OFF / CS",
    lineNumber: 12,
    imageUrl: "https://images.openfoodfacts.org/images/products/002/100/005/5012/front_en.19.400.jpg",
    isSponsored: false,
    sponsoredLabel: null
  },
  {
    productId: "2673640",
    glNumber: "2673640",
    packSize: "8/6 OZ",
    brand: "Louisiana Fish Fry Products",
    title: "Mix, Hush Puppy, Add Water Only",
    rating: 3.8,
    tags: ["cmpContract", "direct"],
    priceCS: 28.00,
    priceEA: 3.50,
    savings: "SAVE $1.10 OFF / CS",
    lineNumber: 13,
    // Hush puppy dry mix — no OFF image found; white bg container will isolate
    imageUrl: "https://images.unsplash.com/photo-1626082927389-c9ba032f3d69?w=200&h=200&fit=fill&fill=solid&fill-color=ffffff",
    isSponsored: false,
    sponsoredLabel: null
  },
  {
    productId: "2673641",
    glNumber: "2673641",
    packSize: "6/2 LB",
    brand: "Mondelez",
    title: "Hush Puppy, Traditional, Frozen, Partfried",
    rating: 3.6,
    tags: ["recentPurchase"],
    priceCS: 52.20,
    priceEA: 8.70,
    savings: "SAVE $2 OFF / CS",
    lineNumber: 14,
    // Frozen appetizer — no OFF image found; white bg container will isolate
    imageUrl: "https://images.unsplash.com/photo-1612440686580-fdf21e0eb786?w=200&h=200&fit=fill&fill=solid&fill-color=ffffff",
    isSponsored: true,
    sponsoredLabel: "Featured"
  },
  {
    productId: "2673642",
    glNumber: "2673642",
    packSize: "12/12 OZ",
    brand: "Applegate Naturals",
    title: "Cheese, American, Yellow, Sliced, Print Wrapped, Organic",
    rating: 3.5,
    tags: ["onML"],
    priceCS: 46.20,
    priceEA: 3.85,
    savings: "SAVE $2 OFF / CS",
    lineNumber: 15,
    imageUrl: "https://images.openfoodfacts.org/images/products/002/531/700/6941/front_en.5.400.jpg",
    isSponsored: false,
    sponsoredLabel: null
  }
];

export const sponsoredCarousel = {
  brandLogoUrl: "https://images.openfoodfacts.org/images/products/007/283/001/1044/front_en.27.400.jpg",
  brandName: "Tillamook",
  title: "Premium Dairy & Cheese Selection",
  subtitle: "Shop Now",
  products: [
    {
      imageUrl: "https://images.openfoodfacts.org/images/products/007/283/001/1044/front_en.27.400.jpg",
      title: "Cheddar, Sharp, Aged, Yellow, Block"
    },
    {
      imageUrl: "https://images.openfoodfacts.org/images/products/004/610/000/1257/front_en.55.400.jpg",
      title: "Mozzarella, Low Moisture, Whole Milk, Block"
    },
    {
      imageUrl: "https://images.openfoodfacts.org/images/products/265/220/100/7074/front_en.3.400.jpg",
      title: "Cheddar, Vermont White, Sliced, Deli Style"
    },
    {
      imageUrl: "https://images.openfoodfacts.org/images/products/002/531/700/6941/front_en.5.400.jpg",
      title: "Cheese, American, Yellow, Sliced, Print Wrapped"
    }
  ]
};
